feat #1 (realease-1.0) : class cat and dog created
nicolasrll/animals-tp pull request #2
Opened 2020-01-26 11:48 UTC by nicolasrll

Close #1

2020-01-26 13:04 UTC, fmoy requested changes

2020-01-26 13:04 UTC, fmoy commented on index.php
> +echo 'Le chat pèse '.$beethoven->getWeight().'kgs.<br>';
beethoven le chat

2020-01-26 13:04 UTC, fmoy commented on index.php
> +require 'Cat.php';
require_once

2020-01-26 13:04 UTC, fmoy commented on index.php
> +echo $garfield->getName();
que se passe t'il si :
`$garfield = new Cat();  
$garfield->setName('Garfield')->setRace('chat de gouttière');  
echo $garfield->getName();`

2020-01-26 13:04 UTC, fmoy commented on Dog.php
> +    private$age;
c'est chaud :)

2020-01-26 13:04 UTC, fmoy commented on Dog.php
> +        $this->setWeight(15);
On evite de la définir dans le construct

2020-01-26 13:04 UTC, fmoy commented on Cat.php
> +    private$age;
sa sent le copier coller a l'arrage pour deux fichiers PHP ? tu peux pas prendre ton temps ?

2020-01-26 17:45 UTC, nicolasrll commented on Cat.php
> +    private$age;
Oui puisque une bonne partie du code est en double. Ca signifie pas que j'ai pas pris mon temps.
En recopiant 2x la même chose j'ai 2x plus de chance de faire des erreur d'écrits
quel est le problème ?

2020-01-26 17:45 UTC, nicolasrll commented on Dog.php
> +    private$age;
je viens de voir l'espace manquant..

2020-01-26 17:46 UTC, fmoy requested changes

2020-01-26 17:46 UTC, fmoy commented on Dog.php
> +    public function setWeight($weight)
un setter sa fait = pas +=

2020-01-27 16:57 UTC, fmoy requested changes

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +        return $this->name;
saut de ligne

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +        if(empty($this->name))
un getter il fait pas de test il retourne la valeur basta :)

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +        if(!is_numeric($quantity))
rolalala et le typage sa sert à quoi ? eating(int $eatAdded)

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +            trigger_error('Veuillez renseigner un nombre pour définir la quantité de nourriture mangé.<br>');
hein ? à retirer

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +            $newWeight = 0;
si getWeight c est 0 pourquoi ne par retourner getWeight ? je vois pas la logique du if else

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +        $this->setWeight($newWeight);
$this->setWeight($this->geteight + $eatAdded);

2020-01-27 16:57 UTC, fmoy commented on Cat.php
> +        return 'Le chat court à une vitesse de '.self::SPEEDING.'km/h';
espacement entre les ' . $va

2020-01-27 16:57 UTC, fmoy commented on Dog.php
> +    public function __construct($name = '', $race = '', $age , $weight = 15)
trop d'espace en signature

2020-01-27 16:57 UTC, fmoy commented on index.php
> +$idefix->setAge('medor');
on fait pas sa on type en signature de méthode on met pas un string dans un int quand tu sauvegarde en bdd sa va planter !

2020-01-27 19:15 UTC, fmoy requested changes

2020-01-27 19:15 UTC, fmoy commented on Cat.php
> +class Cat
saut de ligne

2020-01-27 19:15 UTC, fmoy commented on Cat.php
> +    public function __construct($name='', $race='', $age=0, $weight = 4)
typage

2020-01-27 19:15 UTC, fmoy commented on Cat.php
> +        $this->name = $name;
setter()

2020-01-27 19:15 UTC, fmoy commented on Cat.php
> +        echo 'Vous avez adoptez un nouveau '.strtolower(get_class()).'.<br>';//Il s\'appelle '.$this->name.' et pèse '.$this->weight.'kgs. Il s\'agit d\'un '.$this->race.'. Il est agé de '.$this->age
saut de ligne et on vire le commentaire

2020-01-28 11:56 UTC, nicolasrll commented on Cat.php
> +        return $this->name;
le if est retiré, plus de problème. 
Je retiens

2020-01-28 11:56 UTC, nicolasrll commented on Cat.php
> +        return $this->name;
D'ailleurs j'ai pas compris ton commentaire puisque le if n'est plus présent

2020-02-04 09:30 UTC, fmoy approved these changes

2020-02-04 09:30 UTC, fmoy commented on Cat.php
> +    public function __construct(string $name='',string $race='',int $age=0,int $weight=4)
a revoir

2020-02-04 09:31 UTC, fmoy approved these changes

2020-02-04 10:08 UTC, fmoy approved these changes

2020-02-04 10:20 UTC, fmoy approved these changes

2020-02-04 10:52 UTC, fmoy approved these changes

2020-02-04 10:52 UTC, merged